#!/bin/bash

check_exist() { command -v "$1" > /dev/null 2>&1; }
# print the PID that occupies a port.
# usage: see_port <port number>
see_port() { netstat -lnpt | awk "\$4 ~ /:$1$/ {sub(/\/.*/, \"\", \$7); print \$7}"; }
# usage: summary autotest/results/summary_$DATE/*
summary() { awk '/_mw/ && !/ppdut5|ppchg5/ {print $4}' "$@" | copy; }
# git new branch.
# usage: gnb <new branch name> <upstream branch>
gnb() { git checkout -b "${1:-temp-branch}" "${2:-m/master}"; }
# get ChromeOS branch names.
# usage: get_br <name or prefix of factory/firmware branch> <name or prefix of board>
get_br() { git branch -a | grep -E "${1:-factory}.*-${2:-kukui}.*-.*B$" | head -n1 | xargs; } # xargs to trim whitespace

alias ll='ls -lAhF'
alias rm='rm -i'
alias grep='grep --color=auto'
alias ta='tmux attach -t'
alias zshrc='vim ~/.zshrc'
alias vimrc='vim ~/.vimrc'
alias rsync='rsync -azvhP'
alias rgf='rg --files | rg'
alias trim='sed -e '"'"'s/[[:space:]]*$//'"'"''  # trimming tailing spaces
alias reboot='echo You shall not reboot :P'  # no reboot via commands!
alias shutdown='echo You shall not shutdown :P'  # no shutdown via commands!
check_exist xclip && copy() { DISPLAY=:0 xclip -sel clip; }
check_exist colordiff && alias diff='colordiff'
check_exist tmx2 && alias tmux='tmx2'

# for chromeOS

alias cros_sdk='cd ~/chromiumos/src/; cros_sdk'
alias cr='cros_sdk --no-ns-pid'
alias dut-console='~/chromiumos/src/platform/dev/contrib/dut-console'
alias fac='cd ~/chromiumos/src/platform/factory'
alias ker='cd ~/chromiumos/src/third_party/kernel/v4.19'
alias aut='cd ~/chromiumos/src/third_party/autotest'
alias ec='cd ~/chromiumos/src/platform/ec'
alias faclist='cd ~/chromiumos/src/platform/factory/py/test/test_lists'
alias prilist='cd ~/chromiumos/src/private-overlays/overlay-kukui-private/chromeos-base/factory-board/files/py/test/test_lists'
alias chrome_sdk="cros chrome-sdk --board=kukui --log-level=info --internal --gn-extra-args='enable_nacl=false symbol_level=1 blink_symbol_level=0 is_official_build=false use_goma=true'"
alias rs="repo sync ."
export GOMA_DIR="$HOME/goma"
export PATH=$PATH:~/chromiumos/src/platform/dev/contrib

[[ -f $HOME/.ip_alias ]] && source "$HOME/.ip_alias"

# google3 stuff

alias g3doc='g4d test && cd experimental/users/fshao/g3doc && vim ./sheet.md'
alias x20='cd /google/data/rw/users/fs/fshao'
