#!/bin/bash

# default board name
# shellcheck disable=SC2034
BOARD=kukui
# defuult ChromeOS repository base path
BASE_PATH=''

check_exist() { command -v "$1" > /dev/null 2>&1; }
# print the PID that occupies a port.
# usage: see_port <port number>
see_port() { netstat -lnpt | awk "\$4 ~ /:$1$/ {sub(/\/.*/, \"\", \$7); print \$7}"; }
# usage: summary autotest/results/summary_$DATE/*
summary() { awk '/_mw/ && !/ppdut5|ppchg5/ {print $4}' "$@" | copy; }
# git new branch.
# usage: gnb <new branch name> <upstream branch>
gnb() { git checkout -b "${1:-temp-branch}" "${2:-m/master}"; }
# get ChromeOS branch names.
# usage: get_br <name or prefix of factory/firmware branch> <name or prefix of board>
get_br() { git branch -a | grep -E "${1:-factory}.*-${2:-kukui}.*-.*B$" | head -n1 | xargs; } # xargs to trim whitespace
# get open display for $DISPLAY
get_display() { w -oush | grep -Eo ' :[0-9]+' | uniq | xargs; }

double_confirm() {
  trap return SIGINT
  local i
  echo -n "\nCtrl-C again to exit: "
  for i in {5..1}; do sleep 1; echo -n "$i "; done
}

alias l='ls'
alias ll='ls -lAhF'
alias rm='rm -i'
alias grep='grep --color=auto'
alias ta='tmux attach -t'
alias zshrc='vim ~/.zshrc'
alias vimrc='vim ~/.vimrc'
alias rsync='rsync -azvhP'
alias rgf='rg --files | rg'
alias open='xdg-open'
alias ipython='python3 -m IPython'
alias trim='sed -e '"'"'s/[[:space:]]*$//'"'"''  # trimming tailing spaces
alias reboot='echo You shall not reboot :P'  # no reboot via commands!
alias shutdown='echo You shall not shutdown :P'  # no shutdown via commands!
check_exist xclip && copy() { DISPLAY=$(get_display) xclip -sel clip; }
check_exist colordiff && alias diff='colordiff'
check_exist tmx2 && alias tmux='tmx2'

# ChromeOS path alias & random stuff

if [[ -d $HOME/chromiumos ]]; then
  BASE_PATH="$HOME/chromiumos"
elif [[ -d $HOME/trunk ]]; then
  BASE_PATH="$HOME/trunk"
fi

if [[ -n "$BASE_PATH" ]]; then
  # we're either inside or outside of chroot
  alias cros_sdk='cd ${BASE_PATH}/src/; cros_sdk'
  alias fac='cd ${BASE_PATH}/src/platform/factory'
  alias ker419='cd ${BASE_PATH}/src/third_party/kernel/v4.19'
  alias ker54='cd ${BASE_PATH}/src/third_party/kernel/v5.4'
  alias ker='ker54'
  alias aut='cd ${BASE_PATH}/src/third_party/autotest'
  alias ec='cd ${BASE_PATH}/src/platform/ec'
  alias scr='cd ${BASE_PATH}/src/scripts'
  alias faclist='cd ${BASE_PATH}/src/platform/factory/py/test/test_lists'
  alias pri='cd ${BASE_PATH}/src/private-overlays/overlay-${BOARD}-private'
  alias prilist='cd ${BASE_PATH}/src/private-overlays/overlay-${BOARD}-private/chromeos-base/factory-board/files/py/test/test_lists'
  alias cheets='cd ${BASE_PATH}/src/private-overlays/project-cheets-private/scripts'

  alias rs='repo sync .'
  alias rsa='repo sync -q -j "$(nproc)" -n && repo rebase && repo sync -q -j "$(nproc)" -l --fail-fast'
  export PATH=$PATH:${BASE_PATH}/src/platform/dev/contrib:${BASE_PATH}/chromite/contrib:${BASE_PATH}/src/private-overlays/project-cheets-private/scripts

  if [[ -f $HOME/.ip_alias ]]; then
    source "$HOME/.ip_alias"
  elif [[ -f /outside/.ip_alias ]]; then
    # shellcheck disable=SC1091
    source "/outside/.ip_alias"
  fi

  if [[ -d $HOME/chromiumos ]]; then
    # outside of chroot
    alias cr='cros_sdk --no-ns-pid'
    alias chrome_sdk="cros chrome-sdk --board=kukui --log-level=info --internal --gn-extra-args='enable_nacl=false symbol_level=1 blink_symbol_level=0 is_official_build=false use_goma=true'"
    export GOMA_DIR="$HOME/goma"
  elif [[ -d $HOME/trunk ]]; then
    # inside of chroot
    alias cw='cros_workon'
    alias cwh='cros_workon --host'
    alias cwk='cros-workon-kukui'
    alias g='git'
    alias dut-power='dut-power --vbat-rate=10'
  fi
else
  echo 'No ChromeOS environment detected.'
fi

# google3 stuff

alias g3doc='g4d test && cd experimental/users/fshao/g3doc && vim ./sheet.md'
alias x20='cd /google/data/rw/users/fs/fshao'
