#!/usr/bin/env bash

set -euo pipefail

info() { printf '\e[1;32mINFO:\e[m %s\n' "$*" >&2; }
if_has() { command -v "$1" >/dev/null 2>&1; }

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "$BASEDIR"
git submodule sync --quiet --recursive
git submodule update --init --recursive

# Install symlinks with Dotbot
./install

platform=$(uname -s)
if [[ "$platform" == Linux ]]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  platform=$ID
fi

info "Detected platform: $platform"

case "$platform" in
  Darwin)
    info 'Updating Homebrew'
    brew update
    info 'Installing core packages'
    brew install \
      coreutils \
      font-meslo-lg-nerd-font \
      luarocks \
      mise \
      neovim \
      reattach-to-user-namespace
    ;;
  debian)
    info 'Updating APT packages'
    sudo apt update
    info 'Installing core packages'
    sudo apt install -y \
      luarocks \
      rustup
    ;;
  *)
    printf 'Unsupported platform: %s\n' "$platform" >&2
    exit 1
    ;;
esac

if if_has mise; then
  info 'Installing tools and runtimes via Mise'
  mise install
fi
